
variables:
- group: demo-vm-deploy


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
container:
  endpoint: $[variables['containerRegistry']]
  image: $(containerRegistry).azurecr.io/$(repositoryName):latest
steps:

- script: |
    pwd
    ls
    ansible --version
    packer --version
  displayName: 'Run a multi-line script'
