variables:
- group: demo-vm-deploy

trigger:
- master

stages: 
- template: tasks.yml
  parameters:
    dockerConnection: $(dockerConnection)
    repositoryName: $(repositoryName)
    containerRegistry: $(containerRegistry)