variables:
- group: demo-vm-deploy

trigger:
- master

stages:
- stage: test_1
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
      targetType: filePath
      filePath: test.sh
      env:
        MySecret: $(repositoryName)