variables:
- group: demo-vm-deploy

trigger:
- master

stages:
- stage: test_1
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: Build and Push the Docker image
      inputs:
        azureSubscription: presales-cloud-poc-rg
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript:  |
          az --version
          az account show
          az keyvault secret download --id https://test-vault-presales.vault.azure.net/secrets/github-ssh --file temp
    - bash: ls
    - bash: cat temp

