
variables:
- group: demo-vm-deploy
- name: var2
  value: demovmcontainer

trigger:
- master

jobs:
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: echo $(var2)
  - bash: echo $(containerRegistry)
