
variables:
- group: demo-vm-deploy

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(azureSubscription)
  displayName: Run $[variables.azureSubscription] a one-line script

