name: test1


variables:
- group: test

trigger:
- master

stages: 
  - stage: stage1
    displayName: test stage 1
    jobs:
      - job: job1
        displayName: test job1
        pool:
          vmImage: 'ubuntu-16.04'

        steps:
          - bash: |
              VAR1="literal/${major}/literal/${minor}"
              echo $VAR1

