
variables:
- group: demo-vm-deploy
- name: var2
  value: demovmcontainer

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build
  container:
    endpoint: $(var2)
    image: $(containerRegistry).azurecr.io/$(repositoryName):latest

  steps:
  - script: |
      pwd
      ls
      ansible --version
      packer --version
    displayName: 'Run a multi-line script'
