variables:
- group: demo-vm-deploy

trigger:
- master

stages:
- stage: test_1
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: presales-cloud-poc-rg 
        keyVaultName: test-vault-presales
        secretsFilter: '*'    
    - bash: printenv
    - bash: echo $(github-ssh)
    - bash: cat vars.yml