
variables:
- group: demo-vm-deploy

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: Build and Push the Docker image
  inputs:
    azureSubscription: $(variables.azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(containerRegistry)
