variables:
- group: demo-vm-deploy

trigger:
- master

stages:
- stage: test_1
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: filePath
        filePath: test.ps1
