variables:
- group: demo-vm-deploy

trigger:
- master

stages:
- stage: test_1
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: echo $repositoryName
    - bash: echo $REPOSITORYNAME
    - bash: echo $SUBSCRIPTIONID
    - task: Bash@3
      inputs:
        targetType: filePath
        filePath: test.sh
      env:
        MySecret: $(repositoryName)