parameters:
  dockerConnection: $(dockerConnection)
  repositoryName: $(repositoryName)
  containerRegistry: $(containerRegistry)

stages:
- stage: test_1
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    container:
      image: ${{parameters.containerRegistry}}.azurecr.io/${{parameters.repositoryName}}:latest
      endpoint: ${{parameters.dockerConnection}}
    steps:
    - bash: echo ${{parameters.dockerConnection}}
