variables: 
- group: demo-vm-deploy

parameters:
  name: ''

stages:
- stage: test_1
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    container:
      image: $(containerRegistry).azurecr.io/$(repositoryName):latest
      endpoint: ${{parameters.name}}
    steps:
    - bash: echo ${{parameters.name}}
